// TS_Angular/HW4v1/src/app/components/users/user/components/single-post/single-post.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {Post} from '../../../../../models/post';

@Component({
  selector: 'app-single-post',
  templateUrl: './single-post.component.html',
  styleUrls: ['./single-post.component.css']
})
export class SinglePostComponent implements OnInit {

  @Input() post: Post;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="list-group-item mt-1 rounded shadow">
  <h3 class="display-5">{{post.title}}</h3>
  <small class="text-muted">User ID: {{post.userId}} | Post ID: {{post.id}}</small>
  <hr class="my-4">
  <p>
    {{post.body}}
  </p>
</div>

// React/hw-2/src/components/posts/single-post/single-post.js
import React, {Component} from 'react';

class SinglePost extends Component {

  render() {
    let {userId, id, title, body} = this.props.post;
    return (
      <div>
        <div className="jumbotron m-2 rounded shadow-lg">
          <h1 className="display-4">{title}</h1>
          <p className="lead text-muted">User ID: {userId} | Post ID: {id}</p>
          <hr className="my-2"/>
            <p>{body}</p>
        </div>
      </div>
    );
  }
}

export default SinglePost;
