// React/hw-2/src/components/posts/single-post/single-post.js
import React, {Component} from 'react';

class SinglePost extends Component {

  render() {
    let {userId, id, title, body} = this.props.post;
    return (
      <div>
        <div className="jumbotron m-2 rounded shadow-lg">
          <h1 className="display-4">{title}</h1>
          <p className="lead text-muted">User ID: {userId} | Post ID: {id}</p>
          <hr className="my-2"/>
            <p>{body}</p>
        </div>
      </div>
    );
  }
}

export default SinglePost;

// TS_Angular/HW8/src/app/components/user-posts/components/single-post/single-post.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {Post} from '../../../../models';

@Component({
  selector: 'app-single-post',
  templateUrl: './single-post.component.html',
  styleUrls: ['./single-post.component.css']
})
export class SinglePostComponent implements OnInit {

  @Input() post: Post;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="jumbotron p-4 mb-0 mt-1">
  <h1 class="display-4">{{post.title}}</h1>
  <small class="lead">User ID: {{post.userId}}</small>
  <hr class="my-4">
  <p>{{post.body}}</p>
  <small class="lead">Post ID: {{post.id}}</small>
</div>
