// TS_Angular/HW4/src/app/entity/components/comments/single-comment/single-comment.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-single-comment',
  templateUrl: './single-comment.component.html',
  styleUrls: ['./single-comment.component.css']
})
export class SingleCommentComponent implements OnInit {

  @Input() comment: Comment;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container mt-2">
  <div class="row">
    <div class="col p-3 shadow rounded">
      <h5>
        {{comment.name}}
      </h5>
      <small class="text-muted">email: {{comment.email}}</small>
      <p class="text-justify">
        {{comment.body}}
      </p>
      <small class="text-muted">Comment ID: {{comment.id}}</small> | <small class="text-muted">Post ID: {{comment.postId}}</small>
    </div>
  </div>
</div>

// React/hw-2/src/components/comments/single-comment/single-comment.js
import React, {Component} from 'react';

class SingleComment extends Component {
  render() {

    let {postId, id, name, email, body} = this.props.comment;

    return (
      <div className="jumbotron m-2 rounded shadow-lg">
        <h1 className="display-4">{name}</h1>
        <p className="lead text-muted">Email: {email} | Post ID: {postId} | Comment ID: {id}</p>
        <hr className="my-2"/>
          <p>{body}</p>
      </div>
    );
  }
}

export default SingleComment;
